"use client";

import React, { useState } from "react";
import { 
  Printer, 
  Download, 
  X, 
  Calendar, 
  User, 
  MapPin, 
  Clock, 
  Package, 
  Coins, 
  Boxes, 
  FileText,
  Building2,
  Sparkles
} from "lucide-react";
import { Button } from "@/components/ui/button";

export interface KpiCardData {
  label: string;
  value: string;
  subtitle?: string;
  icon?: any;
  color?: string;
}

export interface ReportGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  reportType: "production_store" | "sales_store" | "orders";
  storeName?: string;
  storeLocation?: string;
  generatedBy?: string;
  kpiCards: KpiCardData[];
  tableHeaders: string[];
  tableRows: (string | number | React.ReactNode)[][];
  // Optional date filtering for Orders
  startDate?: string;
  endDate?: string;
  onDateChange?: (start: string, end: string) => void;
  extraFooterNotes?: string;
}

export default function ReportGeneratorModal({
  isOpen,
  onClose,
  title,
  reportType,
  storeName = "Kampala Main Hub",
  storeLocation = "Kampala Industrial Area, Uganda",
  generatedBy = "System Administrator",
  kpiCards,
  tableHeaders,
  tableRows,
  startDate,
  endDate,
  onDateChange,
  extraFooterNotes
}: ReportGeneratorModalProps) {
  const [filterStartDate, setFilterStartDate] = useState(startDate || new Date().toISOString().split('T')[0]);
  const [filterEndDate, setFilterEndDate] = useState(endDate || new Date().toISOString().split('T')[0]);

  if (!isOpen) return null;

  const currentTimestamp = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true
  });

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    const csvContent = "data:text/csv;charset=utf-8," 
      + [
          [`"Report Title: ${title}"`],
          [`"Generated By: ${generatedBy}"`],
          [`"Generated At: ${currentTimestamp}"`],
          [`"Store: ${storeName} (${storeLocation})"`],
          [],
          tableHeaders.map(h => `"${h}"`).join(","),
          ...tableRows.map(row => row.map(val => `"${typeof val === 'object' ? '' : val}"`).join(","))
        ].join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${reportType}_report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-[999] bg-black/70 backdrop-blur-sm flex items-center justify-center p-2 sm:p-4 overflow-y-auto animate-fadeIn">
      {/* Container Node */}
      <div className="bg-white w-full max-w-[95vw] sm:max-w-7xl rounded-3xl shadow-2xl border border-brand-sage/40 flex flex-col max-h-[92vh] overflow-hidden">
        
        {/* Top Control Bar (Hidden on Print) */}
        <div className="print:hidden bg-gradient-to-r from-brand-forest via-emerald-900 to-brand-forest text-white px-6 py-4 flex items-center justify-between border-b border-brand-sage/20 shrink-0">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-2xl bg-white/10 border border-white/20 flex items-center justify-center text-brand-yellow">
              <FileText size={20} />
            </div>
            <div>
              <h3 className="font-extrabold font-heading text-lg leading-tight flex items-center gap-2">
                {title}
                <span className="bg-brand-yellow text-brand-forest text-[10px] font-black uppercase px-2 py-0.5 rounded-full">
                  Official Statement
                </span>
              </h3>
              <p className="text-[11px] text-emerald-100/80 mt-0.5">
                Executive inventory & logistics report documentation
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              onClick={handlePrint}
              className="bg-brand-yellow hover:bg-brand-yellow/90 text-brand-forest font-black text-xs px-4 h-9.5 rounded-xl gap-2 shadow-sm border-none"
            >
              <Printer size={15} />
              Print / Save PDF
            </Button>
            <Button
              onClick={handleExportCSV}
              variant="outline"
              className="border-white/20 bg-white/10 hover:bg-white/20 text-white text-xs font-bold px-4 h-9.5 rounded-xl gap-2"
            >
              <Download size={15} />
              CSV Export
            </Button>
            <button
              onClick={onClose}
              className="h-9.5 w-9.5 rounded-xl bg-white/10 hover:bg-white/20 flex items-center justify-center text-white/80 hover:text-white transition-all ml-1 cursor-pointer"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Date Filter Bar for Orders Report (Hidden on Print) */}
        {reportType === "orders" && onDateChange && (
          <div className="print:hidden bg-emerald-50/50 border-b border-brand-sage/30 px-6 py-3 flex flex-wrap items-center justify-between gap-3 shrink-0">
            <div className="flex items-center gap-2 text-xs font-bold text-brand-forest">
              <Calendar size={15} className="text-brand-forest" />
              <span>Select Order Report Period:</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-bold text-gray-500">From:</span>
                <input
                  type="date"
                  value={filterStartDate}
                  onChange={(e) => setFilterStartDate(e.target.value)}
                  className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white font-mono text-gray-700"
                />
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-bold text-gray-500">To:</span>
                <input
                  type="date"
                  value={filterEndDate}
                  onChange={(e) => setFilterEndDate(e.target.value)}
                  className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white font-mono text-gray-700"
                />
              </div>
              <Button
                onClick={() => onDateChange(filterStartDate, filterEndDate)}
                className="bg-brand-forest hover:bg-emerald-900 text-white font-bold text-xs h-8 px-3 rounded-lg"
              >
                Apply Filter
              </Button>
            </div>
          </div>
        )}

        {/* Printable Report Document Body */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-10 space-y-8 bg-white print:p-0 print:overflow-visible text-gray-900">
          
          {/* Centered Company Branding & Logo */}
          <div className="text-center border-b border-brand-sage/40 pb-6 space-y-3">
            <div className="inline-flex items-center justify-center h-16 w-16 rounded-2xl bg-brand-forest text-brand-yellow font-black text-2xl shadow-md mb-1 mx-auto">
              LH
            </div>
            <h1 className="text-2xl font-black font-heading text-brand-forest tracking-tight uppercase">
              LOKO Harvest ODS
            </h1>
            <p className="text-xs font-semibold text-gray-500 tracking-widest uppercase">
              Official Enterprise Supply Chain & Inventory Audit Report
            </p>

            {/* Official Metadata Grid */}
            <div className="pt-4 max-w-4xl mx-auto grid grid-cols-2 sm:grid-cols-4 gap-3 text-left bg-brand-sage/10 p-4 rounded-2xl border border-brand-sage/30 text-xs">
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Report Subject</span>
                <span className="font-extrabold text-brand-forest text-xs">{title}</span>
              </div>
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Generated By</span>
                <span className="font-bold text-gray-800 text-xs flex items-center gap-1">
                  <User size={12} className="text-brand-forest" />
                  {generatedBy}
                </span>
              </div>
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Date & Time</span>
                <span className="font-bold text-gray-800 text-xs flex items-center gap-1 font-mono">
                  <Clock size={12} className="text-brand-forest" />
                  {currentTimestamp}
                </span>
              </div>
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Store / Facility</span>
                <span className="font-bold text-gray-800 text-xs flex items-center gap-1">
                  <Building2 size={12} className="text-brand-forest" />
                  {storeName}
                </span>
              </div>
            </div>
          </div>

          {/* KPI Summary Cards Top Banner */}
          <div className="space-y-2">
            <h4 className="text-[11px] font-black uppercase tracking-wider text-brand-forest flex items-center gap-1.5">
              <Sparkles size={14} className="text-brand-yellow" />
              Executive Key Performance Summary
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {kpiCards.map((card, idx) => (
                <div 
                  key={idx}
                  className="bg-gradient-to-br from-brand-sage/15 to-white border border-brand-sage/40 p-4 rounded-2xl shadow-sm relative overflow-hidden"
                >
                  <span className="text-[10px] font-extrabold uppercase tracking-wider text-gray-500 block">
                    {card.label}
                  </span>
                  <div className="text-2xl font-black text-brand-forest font-heading mt-1">
                    {card.value}
                  </div>
                  {card.subtitle && (
                    <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full inline-block mt-1">
                      {card.subtitle}
                    </span>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Full Detailed Data Table */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-[11px] font-black uppercase tracking-wider text-brand-forest">
                Comprehensive Detailed Stock & Movement Audit Ledger ({tableRows.length} Line Items)
              </h4>
              <span className="text-[10px] text-gray-400 font-bold font-mono">
                Facility: {storeLocation}
              </span>
            </div>

            <div className="border border-brand-sage/40 rounded-2xl overflow-x-auto shadow-sm">
              <table className="w-full text-left text-xs min-w-[900px]">
                <thead className="bg-brand-forest text-white uppercase text-[9px] font-black tracking-wider">
                  <tr>
                    {tableHeaders.map((head, idx) => (
                      <th key={idx} className="px-3.5 py-3 border-b border-brand-forest/30 whitespace-nowrap">
                        {head}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 bg-white">
                  {tableRows.length === 0 ? (
                    <tr>
                      <td colSpan={tableHeaders.length} className="px-4 py-8 text-center text-gray-400 italic">
                        No records match the requested report specifications.
                      </td>
                    </tr>
                  ) : (
                    tableRows.map((row, rowIdx) => (
                      <tr 
                        key={rowIdx} 
                        className={rowIdx % 2 === 0 ? "bg-white hover:bg-brand-sage/5" : "bg-gray-50/50 hover:bg-brand-sage/5"}
                      >
                        {row.map((cell, cellIdx) => (
                          <td key={cellIdx} className="px-3.5 py-2.5 text-gray-800 font-medium border-b border-gray-100 whitespace-nowrap">
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Formal Audit Footer */}
          <div className="border-t border-brand-sage/40 pt-6 mt-8 flex flex-col sm:flex-row items-center justify-between text-[10px] text-gray-400 font-medium gap-3">
            <div>
              <p className="font-bold text-gray-600">LOKO Harvest Operational Supply Chain Network</p>
              <p>Location: {storeLocation}</p>
            </div>
            <div className="text-right">
              <p className="font-bold text-brand-forest">Certified Supply Chain Statement</p>
              <p>Generated by: {generatedBy} • {currentTimestamp}</p>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
