"use client";

import React, { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { 
  Printer, 
  Download, 
  X, 
  Calendar, 
  User, 
  MapPin, 
  Clock, 
  Package, 
  Coins, 
  Boxes, 
  FileText,
  Building2,
  Sparkles
} from "lucide-react";
import { Button } from "@/components/ui/button";

export interface KpiCardData {
  label: string;
  value: string;
  subtitle?: string;
  icon?: any;
  color?: string;
}

export interface ReportGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  reportType: "production_store" | "sales_store" | "orders" | "customers" | "customer_ledger";
  storeName?: string;
  storeLocation?: string;
  generatedBy?: string;
  kpiCards: KpiCardData[];
  tableHeaders: string[];
  tableRows: (string | number | React.ReactNode)[][];
  primaryTableTitle?: string;
  // Optional Second Table (e.g. Sales Store Converted Packaged Stock)
  secondTableTitle?: string;
  secondTableHeaders?: string[];
  secondTableRows?: (string | number | React.ReactNode)[][];
  // Optional Damage & Stock Loss Audit Table
  damageAuditTitle?: string;
  damageAuditHeaders?: string[];
  damageAuditRows?: (string | number | React.ReactNode)[][];
  // Optional date filtering for Orders
  startDate?: string;
  endDate?: string;
  onDateChange?: (start: string, end: string) => void;
  // Optional Production Store / Farm interactive filters
  selectedStoreFilter?: string;
  selectedBatchFilter?: string;
  selectedDateFilter?: string;
  storeOptions?: { id: string; name: string }[];
  batchOptions?: string[];
  onStoreFilterChange?: (storeId: string) => void;
  onBatchFilterChange?: (batch: string) => void;
  onDateFilterChange?: (date: string) => void;
  extraFooterNotes?: string;
}

export default function ReportGeneratorModal({
  isOpen,
  onClose,
  title,
  reportType,
  storeName = "Kampala Main Hub",
  storeLocation = "Kampala Industrial Area, Uganda",
  generatedBy = "System Administrator",
  kpiCards,
  tableHeaders,
  tableRows,
  primaryTableTitle,
  secondTableTitle,
  secondTableHeaders,
  secondTableRows,
  damageAuditTitle,
  damageAuditHeaders,
  damageAuditRows,
  startDate,
  endDate,
  onDateChange,
  selectedStoreFilter,
  selectedBatchFilter,
  selectedDateFilter,
  storeOptions,
  batchOptions,
  onStoreFilterChange,
  onBatchFilterChange,
  onDateFilterChange,
  extraFooterNotes
}: ReportGeneratorModalProps) {
  const [filterStartDate, setFilterStartDate] = useState(startDate || new Date().toISOString().split('T')[0]);
  const [filterEndDate, setFilterEndDate] = useState(endDate || new Date().toISOString().split('T')[0]);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!isOpen || !mounted) return null;

  const currentTimestamp = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true
  });

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    let csvContent = "data:text/csv;charset=utf-8," 
      + [
          [`"Report Title: ${title}"`],
          [`"Generated By: ${generatedBy}"`],
          [`"Generated At: ${currentTimestamp}"`],
          [`"Store: ${storeName} (${storeLocation})"`],
          [],
          tableHeaders.map(h => `"${h}"`).join(","),
          ...tableRows.map(row => row.map(val => `"${typeof val === 'object' ? '' : val}"`).join(","))
        ].join("\n");

    if (secondTableHeaders && secondTableRows) {
      csvContent += "\n\n" + [
        [`"Secondary Table: ${secondTableTitle || 'Section 2'}"`],
        secondTableHeaders.map(h => `"${h}"`).join(","),
        ...secondTableRows.map(row => row.map(val => `"${typeof val === 'object' ? '' : val}"`).join(","))
      ].join("\n");
    }

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${reportType}_report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const modalContent = (
    <div id="printable-report-modal-root" className="printable-report-modal-root fixed inset-0 z-[99999] bg-black/70 backdrop-blur-sm flex items-center justify-center p-2 sm:p-4 overflow-y-auto animate-fadeIn">
      {/* Global Print Isolation Styling */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4 landscape;
            margin: 8mm;
          }
          
          /* Hide all main background body children except the portal report modal */
          body > *:not(#printable-report-modal-root) {
            display: none !important;
          }
          
          html, body {
            background: #ffffff !important;
            color: #000000 !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
            height: auto !important;
            overflow: visible !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }

          #printable-report-modal-root,
          .printable-report-modal-root {
            position: absolute !important;
            top: 0 !important;
            left: 0 !important;
            width: 100% !important;
            min-height: 100% !important;
            background: #ffffff !important;
            display: block !important;
            z-index: 9999999 !important;
            padding: 0 !important;
            margin: 0 !important;
            overflow: visible !important;
          }

          .printable-report-card {
            box-shadow: none !important;
            border: none !important;
            border-radius: 0 !important;
            max-width: 100% !important;
            width: 100% !important;
            max-height: none !important;
            height: auto !important;
            overflow: visible !important;
            padding: 0 !important;
            margin: 0 !important;
            background: #ffffff !important;
          }

          .print\\:hidden {
            display: none !important;
          }
        }
      `}</style>

      {/* Container Node */}
      <div className="bg-white w-full max-w-[95vw] sm:max-w-7xl rounded-3xl shadow-2xl border border-brand-sage/40 flex flex-col max-h-[92vh] overflow-hidden printable-report-card">
        
        {/* Top Control Bar (Hidden on Print) */}
        <div className="print:hidden bg-gradient-to-r from-brand-forest via-emerald-900 to-brand-forest text-white px-6 py-4 flex items-center justify-between border-b border-brand-sage/20 shrink-0">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-2xl bg-white/10 border border-white/20 flex items-center justify-center text-brand-yellow">
              <FileText size={20} />
            </div>
            <div>
              <h3 className="font-extrabold font-heading text-lg leading-tight flex items-center gap-2">
                {title}
                <span className="bg-brand-yellow text-brand-forest text-[10px] font-black uppercase px-2 py-0.5 rounded-full">
                  Official Statement
                </span>
              </h3>
              <p className="text-[11px] text-emerald-100/80 mt-0.5">
                Executive inventory & logistics report documentation
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              onClick={handlePrint}
              className="bg-brand-yellow hover:bg-brand-yellow/90 text-brand-forest font-black text-xs px-4 h-9.5 rounded-xl gap-2 shadow-sm border-none"
            >
              <Printer size={15} />
              Print / Save PDF
            </Button>
            <Button
              onClick={handleExportCSV}
              variant="outline"
              className="border-white/20 bg-white/10 hover:bg-white/20 text-white text-xs font-bold px-4 h-9.5 rounded-xl gap-2"
            >
              <Download size={15} />
              CSV Export
            </Button>
            <button
              onClick={onClose}
              className="h-9.5 w-9.5 rounded-xl bg-white/10 hover:bg-white/20 flex items-center justify-center text-white/80 hover:text-white transition-all ml-1 cursor-pointer"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Production Store / Farm Interactive Filter Bar (Hidden on Print) */}
        {reportType === "production_store" && onStoreFilterChange && (
          <div className="print:hidden bg-emerald-50/60 border-b border-brand-sage/30 px-6 py-3 flex flex-wrap items-center justify-between gap-3 shrink-0">
            <div className="flex items-center gap-2 text-xs font-bold text-brand-forest">
              <Building2 size={16} className="text-brand-forest" />
              <span>Select Farm / Store Facility Filter:</span>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              {/* Date Filter */}
              {onDateFilterChange && selectedDateFilter && (
                <div className="flex items-center gap-1.5">
                  <span className="text-[11px] font-bold text-gray-500">Date:</span>
                  <input
                    type="date"
                    value={selectedDateFilter}
                    onChange={(e) => onDateFilterChange(e.target.value)}
                    className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white font-mono text-gray-700 cursor-pointer"
                  />
                </div>
              )}
              {/* Store Options */}
              {storeOptions && (
                <div className="flex items-center gap-1.5">
                  <span className="text-[11px] font-bold text-gray-500">Farm / Store:</span>
                  <select
                    value={selectedStoreFilter || "all"}
                    onChange={(e) => onStoreFilterChange(e.target.value)}
                    className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white text-gray-700 cursor-pointer"
                  >
                    <option value="all">All Farms & Stores</option>
                    {storeOptions.map(store => (
                      <option key={store.id} value={store.id}>{store.name}</option>
                    ))}
                  </select>
                </div>
              )}
              {/* Batch Options */}
              {batchOptions && onBatchFilterChange && (
                <div className="flex items-center gap-1.5">
                  <span className="text-[11px] font-bold text-gray-500">Batch Ref:</span>
                  <select
                    value={selectedBatchFilter || "all"}
                    onChange={(e) => onBatchFilterChange(e.target.value)}
                    className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white text-gray-700 cursor-pointer"
                  >
                    <option value="all">All Batches</option>
                    {batchOptions.map(batch => (
                      <option key={batch} value={batch}>Batch: {batch}</option>
                    ))}
                  </select>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Date Filter Bar for Orders Report (Hidden on Print) */}
        {reportType === "orders" && onDateChange && (
          <div className="print:hidden bg-emerald-50/50 border-b border-brand-sage/30 px-6 py-3 flex flex-wrap items-center justify-between gap-3 shrink-0">
            <div className="flex items-center gap-2 text-xs font-bold text-brand-forest">
              <Calendar size={15} className="text-brand-forest" />
              <span>Select Order Report Period:</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-bold text-gray-500">From:</span>
                <input
                  type="date"
                  value={filterStartDate}
                  onChange={(e) => setFilterStartDate(e.target.value)}
                  className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white font-mono text-gray-700"
                />
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-bold text-gray-500">To:</span>
                <input
                  type="date"
                  value={filterEndDate}
                  onChange={(e) => setFilterEndDate(e.target.value)}
                  className="h-8 px-2 text-xs font-bold border border-brand-sage/60 rounded-lg bg-white font-mono text-gray-700"
                />
              </div>
              <Button
                onClick={() => onDateChange(filterStartDate, filterEndDate)}
                className="bg-brand-forest hover:bg-emerald-900 text-white font-bold text-xs h-8 px-3 rounded-lg"
              >
                Apply Filter
              </Button>
            </div>
          </div>
        )}

        {/* Printable Report Document Body */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-10 space-y-8 bg-white print:p-0 print:overflow-visible text-gray-900">
          
          {/* Centered Company Branding & Logo */}
          <div className="text-center border-b border-brand-sage/40 pb-6 space-y-3">
            <div className="inline-flex items-center justify-center mb-1 mx-auto">
              <img 
                src="/logo/loko.png" 
                alt="LOKO Harvest" 
                className="h-16 w-auto object-contain drop-shadow-sm" 
              />
            </div>
            <h1 className="text-2xl font-black font-heading text-brand-forest tracking-tight uppercase">
              LOKO Harvest ODS
            </h1>
            <p className="text-xs font-semibold text-gray-500 tracking-widest uppercase">
              Official Enterprise Supply Chain & Inventory Audit Report
            </p>

            {/* Official Metadata Grid */}
            <div className="pt-4 max-w-4xl mx-auto grid grid-cols-2 sm:grid-cols-4 gap-3 text-left bg-brand-sage/10 p-4 rounded-2xl border border-brand-sage/30 text-xs">
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Report Subject</span>
                <span className="font-extrabold text-brand-forest text-xs">{title}</span>
              </div>
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Generated By</span>
                <span className="font-bold text-gray-800 text-xs flex items-center gap-1">
                  <User size={12} className="text-brand-forest" />
                  {generatedBy}
                </span>
              </div>
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Date & Time</span>
                <span className="font-bold text-gray-800 text-xs flex items-center gap-1 font-mono">
                  <Clock size={12} className="text-brand-forest" />
                  {currentTimestamp}
                </span>
              </div>
              <div>
                <span className="text-[10px] font-extrabold uppercase text-gray-400 block tracking-wider">Store / Facility</span>
                <span className="font-bold text-gray-800 text-xs flex items-center gap-1">
                  <Building2 size={12} className="text-brand-forest" />
                  {storeName}
                </span>
              </div>
            </div>
          </div>

          {/* KPI Summary Cards Top Banner */}
          <div className="space-y-2">
            <h4 className="text-[11px] font-black uppercase tracking-wider text-brand-forest flex items-center gap-1.5">
              <Sparkles size={14} className="text-brand-yellow" />
              Executive Key Performance Summary
            </h4>
            <div className={`grid grid-cols-2 ${kpiCards.length === 3 ? 'sm:grid-cols-3' : 'sm:grid-cols-4'} gap-3`}>
              {kpiCards.map((card, idx) => (
                <div 
                  key={idx}
                  className="bg-gradient-to-br from-brand-sage/15 to-white border border-brand-sage/40 p-4 rounded-2xl shadow-sm relative overflow-hidden"
                >
                  <span className="text-[10px] font-extrabold uppercase tracking-wider text-gray-500 block">
                    {card.label}
                  </span>
                  <div className="text-2xl font-black text-brand-forest font-heading mt-1">
                    {card.value}
                  </div>
                  {card.subtitle && (
                    <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full inline-block mt-1">
                      {card.subtitle}
                    </span>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Primary Table (Production Store or Sales Store Bulk Inflow) */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-[11px] font-black uppercase tracking-wider text-brand-forest">
                {primaryTableTitle || `Comprehensive Detailed Stock & Movement Audit Ledger (${tableRows.length} Line Items)`}
              </h4>
              <span className="text-[10px] text-gray-400 font-bold font-mono">
                Facility: {storeLocation}
              </span>
            </div>

            <div className="border border-brand-sage/40 rounded-2xl overflow-hidden shadow-sm print:rounded-none print:shadow-none print:border-gray-300 print:overflow-visible">
              <table className="w-full text-left text-[9.5px] border-collapse">
                <thead className="bg-brand-forest text-white uppercase text-[8.5px] font-black tracking-wider">
                  <tr>
                    {tableHeaders.map((head, idx) => (
                      <th key={idx} className="px-2 py-2.5 border-b border-brand-forest/30 whitespace-nowrap">
                        {head}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 bg-white">
                  {tableRows.length === 0 ? (
                    <tr>
                      <td colSpan={tableHeaders.length} className="px-4 py-8 text-center text-gray-400 italic">
                        No records match the requested report specifications.
                      </td>
                    </tr>
                  ) : (
                    tableRows.map((row, rowIdx) => (
                      <tr 
                        key={rowIdx} 
                        className={rowIdx % 2 === 0 ? "bg-white hover:bg-brand-sage/5" : "bg-gray-50/50 hover:bg-brand-sage/5"}
                      >
                        {row.map((cell, cellIdx) => (
                          <td key={cellIdx} className="px-2 py-1.5 text-gray-800 font-medium border-b border-gray-100 whitespace-nowrap">
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Optional Secondary Table (e.g. Sales Store Converted Packaged Stock) */}
          {secondTableHeaders && secondTableRows && (
            <div className="space-y-3 pt-6 border-t border-brand-sage/40">
              <div className="flex items-center justify-between">
                <h4 className="text-[11px] font-black uppercase tracking-wider text-brand-forest">
                  {secondTableTitle || `Sales Store Converted Packaged Stock Ledger (${secondTableRows.length} Line Items)`}
                </h4>
                <span className="text-[10px] text-gray-400 font-bold font-mono">
                  Converted Packs & Cartons Breakdown
                </span>
              </div>

              <div className="border border-brand-sage/40 rounded-2xl overflow-hidden shadow-sm print:rounded-none print:shadow-none print:border-gray-300 print:overflow-visible">
                <table className="w-full text-left text-[9.5px] border-collapse">
                  <thead className="bg-emerald-950 text-brand-yellow uppercase text-[8.5px] font-black tracking-wider">
                    <tr>
                      {secondTableHeaders.map((head, idx) => (
                        <th key={idx} className="px-2 py-2.5 border-b border-emerald-900 whitespace-nowrap">
                          {head}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 bg-white">
                    {secondTableRows.length === 0 ? (
                      <tr>
                        <td colSpan={secondTableHeaders.length} className="px-4 py-8 text-center text-gray-400 italic">
                          No converted packaged stock records found.
                        </td>
                      </tr>
                    ) : (
                      secondTableRows.map((row, rowIdx) => (
                        <tr 
                          key={rowIdx} 
                          className={rowIdx % 2 === 0 ? "bg-white hover:bg-brand-sage/5" : "bg-gray-50/50 hover:bg-brand-sage/5"}
                        >
                          {row.map((cell, cellIdx) => (
                            <td key={cellIdx} className="px-2 py-1.5 text-gray-800 font-medium border-b border-gray-100 whitespace-nowrap">
                              {cell}
                            </td>
                          ))}
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Optional Damage & Stock Loss Breakdown Table */}
          {damageAuditHeaders && damageAuditRows && (
            <div className="space-y-3 pt-6 border-t border-brand-sage/40">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <h4 className="text-[11px] font-black uppercase tracking-wider text-red-900 flex items-center gap-1.5">
                    <span className="h-2 w-2 rounded-full bg-red-600 animate-pulse" />
                    {damageAuditTitle || `Detailed Damage & Stock Loss Audit Ledger (${damageAuditRows.length} Line Items)`}
                  </h4>
                </div>
                <span className="text-[10px] text-red-700 font-bold font-mono bg-red-50 px-2.5 py-0.5 rounded-full border border-red-200">
                  Damage Declarations, Types, Reasons & Photo Evidence Audit
                </span>
              </div>

              <div className="border border-red-200 rounded-2xl overflow-hidden shadow-sm print:rounded-none print:shadow-none print:border-gray-300 print:overflow-visible">
                <table className="w-full text-left text-[9.5px] border-collapse">
                  <thead className="bg-red-900 text-white uppercase text-[8.5px] font-black tracking-wider">
                    <tr>
                      {damageAuditHeaders.map((head, idx) => (
                        <th key={idx} className="px-2.5 py-2.5 border-b border-red-800 whitespace-nowrap">
                          {head}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-red-100 bg-white">
                    {damageAuditRows.length === 0 ? (
                      <tr>
                        <td colSpan={damageAuditHeaders.length} className="px-4 py-8 text-center text-gray-400 italic">
                          No damages or stock loss declarations recorded for the selected report filters.
                        </td>
                      </tr>
                    ) : (
                      damageAuditRows.map((row, rowIdx) => (
                        <tr 
                          key={rowIdx} 
                          className={rowIdx % 2 === 0 ? "bg-white hover:bg-red-50/40" : "bg-red-50/20 hover:bg-red-50/40"}
                        >
                          {row.map((cell, cellIdx) => (
                            <td key={cellIdx} className="px-2.5 py-2 text-gray-800 font-medium border-b border-red-50 whitespace-normal">
                              {cell}
                            </td>
                          ))}
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Formal Audit Footer */}
          <div className="border-t border-brand-sage/40 pt-6 mt-8 flex flex-col sm:flex-row items-center justify-between text-[10px] text-gray-400 font-medium gap-3">
            <div>
              <p className="font-bold text-gray-600">LOKO Harvest Operational Supply Chain Network</p>
              <p>Location: {storeLocation}</p>
            </div>
            <div className="text-right">
              <p className="font-bold text-brand-forest">Certified Supply Chain Statement</p>
              <p>Generated by: {generatedBy} • {currentTimestamp}</p>
            </div>
          </div>

        </div>

      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
}
